#pragma once

#include <winsock2.h>
#include <ws2tcpip.h>
#include <in6addr.h>
#include <tchar.h>
#include <ws2ipdef.h>
#include <IPHlpApi.h>
#include <Mstcpip.h>
#include <WinDNS.h>

#include <memory>
#include <iostream>
#include <iomanip>
#include <chrono>
#include <thread>
#include <limits>
#include <atomic>
#include <string>
#include <functional>
#include <vector>
#include <cassert>
#include <array>
#include <map>
#include <cctype>
#include <mutex>
#include <shared_mutex>
#include <variant>
#include <bitset>
#include <optional>
#include <algorithm>
#include <fstream>
#include <charconv>
#include <gsl/gsl>

#include <common.h>
#include <ndisapi.h>

#include <iphlp.h>
#include <winsys/object.h>
#include <winsys/event.h>
#include <net/mac_address.h>
#include <net/ip_address.h>
#include <net/ip_endpoint.h>
#include <net/ipv6_helper.h>
#include <pcap/pcap.h>
#include <pcap/pcap_file_storage.h>
#include <net/ip_subnet.h>
#include <iphelper/network_adapter_info.h>
#include <iphelper/process_lookup.h>
#include <ndisapi/network_adapter.h>
#include <ndisapi/fastio_packet_filter.h>
#include <ndisapi/dual_packet_filter.h>
#include <tools/strings.h>
